"""
Component lookup service for rule generation.

This module provides the ComponentLookup class which:
1. Builds a cache of all components from treeJson for quick lookup
2. Provides methods to search and retrieve component information
3. Formats component data for use in rule generation (matching VariableDefinition.toJson() structure)
"""

import logging
from typing import Dict, Any, Optional, List

logger = logging.getLogger(__name__)


class ComponentLookup:
    """Service to look up component information and format it for rules."""

    def __init__(
        self,
        tree_json: Dict[str, Any],
        functions_config: Optional[List[Dict[str, Any]]] = None
    ):
        """
        Initialize with form tree JSON and optional functions configuration.

        Args:
            tree_json: The complete form tree JSON structure (from transform-form.js).
            functions_config: Optional list of function definitions.
        """
        self.tree_json = tree_json
        self.functions_config = functions_config or []
        self._component_cache: Dict[str, Dict[str, Any]] = {}
        self._functions_cache: Dict[str, Dict[str, Any]] = {}
        self._build_component_cache()
        self._build_functions_cache()

    def _build_component_cache(self):
        """Build a cache of all components for quick lookup."""

        def traverse(node: Dict[str, Any], parent_id: str = "", display_path: str = "FORM/"):
            if not node:
                return

            node_id = node.get("id", "")
            node_name = node.get("name", "")
            display_name = node.get("displayName", node.get("name", ""))

            # Build metadata object with isAncestorRepeatable
            metadata = {}
            if "isAncestorRepeatable" in node:
                metadata["isAncestorRepeatable"] = node.get("isAncestorRepeatable", False)
            # Merge with any existing metadata
            if node.get("metadata"):
                metadata.update(node.get("metadata"))

            if node_id:
                # Store component info - ALWAYS use the full type from treeJson
                # The treeJson type is generated by _getExpEditorDataType() in ExpressionEditorTree.js
                # and contains the full pipe-delimited type (e.g., "AFCOMPONENT|FIELD|TEXT FIELD|STRING")
                original_type = node.get("type", "")
                component_type = original_type if original_type else self._get_fallback_type(node)

                self._component_cache[node_id] = {
                    "id": node_id,
                    "name": node_name,
                    "displayName": display_name,
                    "type": component_type,
                    "displayPath": display_path,
                    "parent": parent_id,
                    "fieldType": node.get("fieldType", ""),
                    "path": node.get("path", ""),
                    "isDuplicate": False,
                    "metadata": metadata
                }

                # Also store by name for easier lookup
                if node_name and node_name != node_id:
                    self._component_cache[node_name] = self._component_cache[node_id]

            # Traverse children - use child's displayName for path
            items = node.get("items", [])
            if items and isinstance(items, list):
                for item in items:
                    item_display_name = item.get("displayName", item.get("name", ""))
                    child_display_path = f"{display_path}{item_display_name}/"
                    traverse(item, node_id, child_display_path)

        traverse(self.tree_json)
        logger.debug(f"Built component cache with {len(self._component_cache)} entries")

    def _build_functions_cache(self):
        """Build a cache of all functions for quick lookup."""
        if not self.functions_config:
            return

        for func in self.functions_config:
            func_id = func.get('id', '')
            if func_id:
                self._functions_cache[func_id] = func
                # Also store by displayName for easier lookup
                display_name = func.get('displayName', '')
                if display_name:
                    self._functions_cache[display_name.lower()] = func

        logger.debug(f"Built functions cache with {len(self._functions_cache)} entries")

    def _get_fallback_type(self, node: Dict[str, Any]) -> str:
        """
        Generate full pipe-delimited type string as fallback when not present in treeJson.

        This mirrors the _getExpEditorDataType() function from ExpressionEditorTree.js.
        The type format is: AFCOMPONENT|FIELD|<FIELD_TYPE>|<DATA_TYPE>

        Only used as fallback when treeJson doesn't have the type already.
        """
        field_type = node.get("fieldType", "")
        data_type = node.get("type", "string")  # JSON schema type

        # Form is special - just returns "FORM"
        if field_type == "form":
            return "FORM"

        # Build the type array like ExpressionEditorTree.js does
        type_parts = ["AFCOMPONENT"]

        # Field types that are considered "fields" (not panels, images, etc.)
        field_types = ["text-input", "multiline-input", "email", "number-input",
                       "date-input", "drop-down", "radio-group", "checkbox-group",
                       "checkbox", "button", "file-input", "captcha"]

        if field_type in field_types:
            type_parts.append("FIELD")

        # Map fieldType to specific type names
        field_type_mapping = {
            "text-input": ["TEXT FIELD"],
            "multiline-input": ["TEXT FIELD"],
            "email": ["TEXT FIELD"],
            "number-input": ["NUMBER FIELD"],
            "date-input": ["DATE FIELD"],
            "drop-down": ["DROPDOWN"],
            "radio-group": ["RADIO BUTTON"],
            "checkbox-group": ["CHECK BOX"],
            "checkbox": [],
            "button": ["BUTTON"],
            "file-input": ["FILE ATTACHMENT", "BINARY"],
            "panel": ["PANEL"],
            "plain-text": ["STATIC TEXT", "STRING"],
            "image": ["IMAGE", "STRING"],
            "captcha": []
        }

        if field_type in field_type_mapping:
            type_parts.extend(field_type_mapping[field_type])

        # Add data type based on JSON schema type (skip for button)
        if field_type != "button":
            if data_type in ["number", "integer"]:
                type_parts.append("NUMBER")
            elif data_type == "boolean":
                type_parts.append("BOOLEAN")
            elif data_type == "string":
                # Check for date format
                if node.get("format") == "date":
                    type_parts.append("DATE")
                elif field_type in field_types:
                    type_parts.append("STRING")
            elif data_type in ["number[]", "string[]", "boolean[]"]:
                type_parts.append(data_type.upper())
            elif data_type == "file":
                type_parts.append("FILE")
            elif data_type == "file[]":
                type_parts.append("FILE[]")

        return "|".join(type_parts)

    def get_component(
        self,
        identifier: str
    ) -> Optional[Dict[str, Any]]:
        """
        Get component information by ID or name.

        Returns the full type from treeJson (e.g., "AFCOMPONENT|FIELD|TEXT FIELD|STRING").
        This is the preferred approach - use the full type everywhere for consistency.

        Args:
            identifier: Component ID or name.

        Returns:
            Component info dict matching VariableDefinition.toJson() structure:
            {id, displayName, type, isDuplicate, displayPath, name, parent, metadata}
            or None if not found.
        """
        component = self._component_cache.get(identifier)
        if not component:
            logger.warning(f"Component not found: {identifier}")
            return None

        # Return structure matching exp-editor/rule-builder/core/VariableDefinition.js toJson()
        result = {
            "id": component["id"],
            "displayName": component["displayName"],
            "type": component["type"],  # Always use full type from treeJson
            "isDuplicate": component["isDuplicate"],
            "displayPath": component["displayPath"],
            "name": component["name"],
            "parent": component["parent"]
        }

        # Add metadata if it has properties
        metadata = component.get("metadata", {})
        if metadata:
            result["metadata"] = metadata

        return result

    def get_component_for_action(self, identifier: str) -> Optional[Dict[str, Any]]:
        """
        Get component info for use in action statements (HIDE, SHOW, ENABLE, etc.).

        Returns the full type from treeJson (e.g., "AFCOMPONENT|FIELD|TEXT FIELD|STRING").
        This preserves the complete type information for grammar validation.

        Args:
            identifier: Component ID or name.

        Returns:
            Component info dict with full type from treeJson.
        """
        return self.get_component(identifier)  # Use full type, no override

    def get_component_for_value_field(self, identifier: str) -> Optional[Dict[str, Any]]:
        """
        Get component info for use in SET_VALUE_STATEMENT target (VALUE_FIELD).

        Returns the full type from treeJson (e.g., "AFCOMPONENT|FIELD|TEXT FIELD|STRING").
        This preserves the complete type information for grammar validation.

        Args:
            identifier: Component ID or name.

        Returns:
            Component info dict with full type from treeJson.
        """
        return self.get_component(identifier)

    def search_components(self, query: str) -> List[Dict[str, Any]]:
        """
        Search for components by partial name or display name.

        Args:
            query: Search query.

        Returns:
            List of matching components.
        """
        query_lower = query.lower()
        results = []
        seen_ids = set()

        for key, component in self._component_cache.items():
            comp_id = component.get("id", "")
            if comp_id in seen_ids:
                continue

            if (query_lower in component.get("name", "").lower() or
                query_lower in component.get("displayName", "").lower()):
                results.append({
                    "id": component["id"],
                    "displayName": component["displayName"],
                    "type": component["type"],
                    "displayPath": component["displayPath"],
                    "name": component["name"],
                    "parent": component["parent"],
                    "fieldType": component.get("fieldType", "")
                })
                seen_ids.add(comp_id)

        return results

    def list_all_components(self) -> List[Dict[str, Any]]:
        """
        List all available components.

        Returns:
            List of all components.
        """
        results = []
        seen_ids = set()

        for key, component in self._component_cache.items():
            comp_id = component.get("id", "")
            if comp_id and comp_id not in seen_ids:
                results.append({
                    "id": component["id"],
                    "displayName": component["displayName"],
                    "type": component["type"],
                    "name": component["name"],
                    "fieldType": component.get("fieldType", "")
                })
                seen_ids.add(comp_id)

        return results

    def get_form_component(self) -> Optional[Dict[str, Any]]:
        """
        Get the root form component ($form).

        Returns:
            Form component info dict.
        """
        return self.get_component("$form")

    def get_function_info(self, function_identifier: str) -> Optional[Dict[str, Any]]:
        """
        Get complete function definition including all arg descriptions.

        IMPORTANT: Use this to get the exact args[] array for FUNCTION_CALL.
        The returned functionName structure should be copied EXACTLY to FUNCTION_CALL.functionName.

        Args:
            function_identifier: Function id or displayName.

        Returns:
            Complete function definition with structure matching FUNCTION_CALL.functionName:
            {id, displayName, type, isDuplicate, displayPath, args, impl}
            or None if not found.
        """
        func = None

        # Try direct lookup first
        if function_identifier in self._functions_cache:
            func = self._functions_cache[function_identifier]
        # Try lowercase lookup
        elif function_identifier.lower() in self._functions_cache:
            func = self._functions_cache[function_identifier.lower()]
        else:
            # Try partial match
            for key, f in self._functions_cache.items():
                if function_identifier.lower() in key.lower():
                    func = f
                    break
                if function_identifier.lower() in f.get('id', '').lower():
                    func = f
                    break
                if function_identifier.lower() in f.get('displayName', '').lower():
                    func = f
                    break

        if not func:
            return None

        # Return structure matching FUNCTION_CALL.functionName format
        return {
            "id": func.get("id", ""),
            "displayName": func.get("displayName", ""),
            "type": func.get("type", "VOID"),
            "isDuplicate": False,
            "displayPath": "",
            "args": func.get("args", []),
            "impl": func.get("impl", "")
        }

    def search_functions(self, query: str) -> List[Dict[str, Any]]:
        """
        Search for functions by partial name or description.

        Args:
            query: Search query.

        Returns:
            List of matching functions.
        """
        query_lower = query.lower()
        results = []
        seen_ids = set()

        for key, func in self._functions_cache.items():
            func_id = func.get("id", "")
            if func_id in seen_ids:
                continue

            if (query_lower in func.get("id", "").lower() or
                query_lower in func.get("displayName", "").lower() or
                query_lower in func.get("description", "").lower()):
                results.append(func)
                seen_ids.add(func_id)

        return results

    def list_all_functions(self) -> List[Dict[str, Any]]:
        """
        List all available functions with their full definitions.

        Returns:
            List of all functions with complete args arrays.
        """
        results = []
        seen_ids = set()

        for key, func in self._functions_cache.items():
            func_id = func.get("id", "")
            if func_id and func_id not in seen_ids:
                results.append(func)
                seen_ids.add(func_id)

        return results
